### ISSUE TITLE
Open Spacewar on steam

### ISSUE THREAD

**Issue by ChocoScaff** [EpicMorg/UniversalValveToolbox#35]

**Comment by stamepicmorg** [comment]
@ChocoScaff hello. please describe your problem. but let me guess

i think it is not a bug, it is a "feature".  ToolBox need some SteamAppId (480=space war) to initialize steam api. Because toolbox don't have own SteamAppId.

if toolbox will use SteamAppId of selected game from list - some games will not launch. but if faked "space war" is running - you could safely run any engines or games in parallel.

480's id is dev-stub from valve.
